<a href="https://colab.research.google.com/github/SLucy0/Data_Analytics/blob/main/Final_filtered_NOAA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import pandas as pd
import numpy as np
import seaborn as sns

url = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2012_c20260323.csv.gz"
df = pd.read_csv(url, compression='gzip')
df.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201210,29,1600,201210,29,1922,68680,416744,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sandy, a hybrid storm with both tropical and e...",The Automated Surface Observing System at Manc...,CSV
1,201203,1,0,201203,1,1900,60347,364656,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Several waves of low pressure moved south of s...,Seven to twelve inches of snow fell across eas...,CSV
2,201202,29,1400,201202,29,2359,60343,364655,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Several waves of low pressure moved south of s...,Seven to twelve inches of snow fell across eas...,CSV
3,201212,26,2000,201212,27,1800,70995,426679,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Low pressure moved up the coast over Southern ...,Six to eight inches of snow fell across easter...,CSV
4,201212,29,1600,201212,30,1200,71061,427044,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A rapidly intensifying low moved out of the mi...,Snowfall totals between four and eight inches ...,CSV

In [43]:
hurricane_sandy_filtered_df = final_filtered_df[final_filtered_df['EPISODE_NARRATIVE'].str.contains('Sandy', na=False)]
print("Hurricane Sandy events in NY, NJ, CT, PA between Oct 29-30:")
display(hurricane_sandy_filtered_df.head())

unique_dates_hurricane_sandy = hurricane_sandy_filtered_df['DATE'].unique()
print("\nUnique dates in hurricane_sandy_filtered_df:")
for date in unique_dates_hurricane_sandy:
    print(f"- {date.strftime('%Y-%m-%d')}")

Hurricane Sandy events in NY, NJ, CT, PA between Oct 29-30:

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE,DATE
12484,201210,29,1900,201210,29,2300,68866,413112,NEW JERSEY,34,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust up to 80 mph was reported in Clift...,CSV,2012-10-29
12752,201210,29,1500,201210,29,2100,68867,415922,NEW YORK,36,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust to 81 mph was reported in East Mor...,CSV,2012-10-29
12753,201210,29,1300,201210,29,2000,68867,415923,NEW YORK,36,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust up to 85 mph was reported near Plu...,CSV,2012-10-29
12754,201210,29,1700,201210,29,2200,68867,416831,NEW YORK,36,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust of 74 mph was measured at LaGuardi...,CSV,2012-10-29
12995,201210,29,1800,201210,29,2200,68866,413118,NEW JERSEY,34,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust up to 77 mph was reported near Bay...,CSV,2012-10-29

Unique dates in hurricane_sandy_filtered_df:
- 2012-10-29
- 2012-10-30

In [44]:
unique_states_sandy = hurricane_sandy_filtered_df['STATE'].unique()
print("Unique states in hurricane_sandy_filtered_df:")
for state in unique_states_sandy:
    print(f"- {state}")

Unique states in hurricane_sandy_filtered_df:
- NEW JERSEY
- NEW YORK
- PENNSYLVANIA
- CONNECTICUT

In [45]:
unique_event_types_sandy = hurricane_sandy_filtered_df['EVENT_TYPE'].unique()
print("Unique Event Types in Hurricane Sandy Filtered Data:")
for event_type in unique_event_types_sandy:
    print(f"- {event_type}")

Unique Event Types in Hurricane Sandy Filtered Data:
- High Wind
- Coastal Flood
- Flood
- Strong Wind
- Heavy Snow
- Storm Surge/Tide

In [46]:
df['DATE'] = pd.to_datetime(df['BEGIN_YEARMONTH'].astype(str) + df['BEGIN_DAY'].astype(str), format='%Y%m%d')
display(df.head())

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE,DATE
0,201210,29,1600,201210,29,1922,68680,416744,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,"Sandy, a hybrid storm with both tropical and e...",The Automated Surface Observing System at Manc...,CSV,2012-10-29
1,201203,1,0,201203,1,1900,60347,364656,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,Several waves of low pressure moved south of s...,Seven to twelve inches of snow fell across eas...,CSV,2012-03-01
2,201202,29,1400,201202,29,2359,60343,364655,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,Several waves of low pressure moved south of s...,Seven to twelve inches of snow fell across eas...,CSV,2012-02-29
3,201212,26,2000,201212,27,1800,70995,426679,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,Low pressure moved up the coast over Southern ...,Six to eight inches of snow fell across easter...,CSV,2012-12-26
4,201212,29,1600,201212,30,1200,71061,427044,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,A rapidly intensifying low moved out of the mi...,Snowfall totals between four and eight inches ...,CSV,2012-12-29

In [47]:
start_date = '2012-10-29'
end_date = '2012-10-30'

dates_filtered_df = df[(df['DATE'] >= start_date) & (df['DATE'] <= end_date)]
display(dates_filtered_df.head())

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE,DATE
0,201210,29,1600,201210,29,1922,68680,416744,NEW HAMPSHIRE,33,...,NaN,NaN,NaN,NaN,NaN,NaN,"Sandy, a hybrid storm with both tropical and e...",The Automated Surface Observing System at Manc...,CSV,2012-10-29
116,201210,29,900,201210,30,1200,69638,417854,PUERTO RICO,99,...,NaN,NaN,NaN,NaN,NaN,NaN,Large long period northwest swells associated ...,Large and long period swell flooded calle Mari...,CSV,2012-10-29
117,201210,29,900,201210,30,1200,69638,417855,PUERTO RICO,99,...,NaN,NaN,NaN,NaN,NaN,NaN,Large long period northwest swells associated ...,Large and long period northwest swell flooded ...,CSV,2012-10-29
157,201210,30,1600,201210,30,1600,69639,417857,PUERTO RICO,99,...,W,AGUADILLA,18.4700,-67.120,18.4694,-67.1448,A southwest to south low level flow transporte...,Several power lines down in coastal area along...,CSV,2012-10-30
218,201210,30,1604,201210,30,1604,69639,417858,PUERTO RICO,99,...,S,VEGA ALTA,18.3957,-66.346,18.3898,-66.3285,A southwest to south low level flow transporte...,Numerous trees and power lines down in Vega Al...,CSV,2012-10-30

In [49]:
target_states = ['NEW YORK', 'NEW JERSEY', 'CONNECTICUT', 'PENNSYLVANIA']

final_filtered_df = dates_filtered_df[dates_filtered_df['STATE'].isin(target_states)]
display(final_filtered_df.head())

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE,DATE
12484,201210,29,1900,201210,29,2300,68866,413112,NEW JERSEY,34,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust up to 80 mph was reported in Clift...,CSV,2012-10-29
12752,201210,29,1500,201210,29,2100,68867,415922,NEW YORK,36,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust to 81 mph was reported in East Mor...,CSV,2012-10-29
12753,201210,29,1300,201210,29,2000,68867,415923,NEW YORK,36,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust up to 85 mph was reported near Plu...,CSV,2012-10-29
12754,201210,29,1700,201210,29,2200,68867,416831,NEW YORK,36,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust of 74 mph was measured at LaGuardi...,CSV,2012-10-29
12995,201210,29,1800,201210,29,2200,68866,413118,NEW JERSEY,34,...,NaN,NaN,NaN,NaN,NaN,NaN,Post Tropical Storm Sandy was the costliest na...,A wind gust up to 77 mph was reported near Bay...,CSV,2012-10-29

In [50]:
output_file_path = 'final_filtered_data.csv'
final_filtered_df.to_csv(output_file_path, index=False)
print(f"DataFrame successfully exported to '{output_file_path}'")

DataFrame successfully exported to 'final_filtered_data.csv'

In [51]:
event_type_counts = final_filtered_df['EVENT_TYPE'].value_counts()
print("Event Type Occurrences in final_filtered_df:")
display(event_type_counts)

Event Type Occurrences in final_filtered_df:

EVENT_TYPE
High Wind           147
Coastal Flood        35
Flood                32
Strong Wind          24
Storm Surge/Tide      9
Heavy Snow            3
Name: count, dtype: int64